version: 2.1

default: &dflt
  docker: 
    - image: circleci/node:13.8.0
  working_directory: /project



jobs:
  build:
    <<: *dflt
    steps:
      - checkout
      - run: npm i
      - save_cache:
            key: "npm_package" 
            paths: 
              - /src/node_modules
      - run: npm run build
          
  run_test:
    <<: *dflt
    steps:
      - checkout
      - restore_cache:
          key: "npm_package"
      - run: npm i
      - run: npm run test

  analyze:
    <<: *dflt
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_package"
      - run : npm i
      - run: npm audit   

workflows:
  jobs_flow:
    jobs:
      - build
      - run_test:
          requires: 
            - build
      - analyze:
          requires:
            - run_test